# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSConvCTCModule
  in_features: 165 # freq * channels = (n_fft=64 // 2 + 1) * 5
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32 # Total temporal receptive field of 125 samples given 4 layers
  electrode_channels: 5

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000 # 4 sec windows for 2kHz EMG
  padding: [1800, 200] # 900ms past context, 100ms future context
