# @package _global_
module:
  _target_: emg2qwerty.lightning.TDSConvCTCWithAutoencoderModule
  in_features: 264 # freq * channels = (n_fft // 2 + 1) * 8
  mlp_features: [384]
  block_channels: [24, 24, 24, 24]
  kernel_width: 32 # Total temporal receptive field of 125 samples given 4 layers
  electrode_channels: 8
  autoencoder_checkpoint: path/to/autoencoder/checkpoint.ckpt
  freeze_encoder: True
  multi_scale: True

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000 # 4 sec windows for 2kHz EMG
  padding: [1800, 200] # 900ms past context, 100ms future context
