defaults:
  - user: generic
  - transforms: log_spectrogram
  - model: tds_conv_ctc
  - optimizer: adam
  - lr_scheduler: linear_warmup_cosine_annealing
  - decoder: ctc_greedy
  - cluster: local
  - _self_

seed: 1501
batch_size: 32
num_workers: 4 # Number of workers for dataloading
train: True # Whether to train or only run validation and test
checkpoint: null # Optional path to checkpoint file
monitor_metric: val/CER
monitor_mode: min
reduced: False

trainer:
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 150
  default_root_dir: ${hydra:runtime.output_dir}

callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${hydra:runtime.output_dir}/checkpoints/${model._target_.split(".")[-1]}
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    save_last: True
    verbose: True
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: ${monitor_metric}
    mode: ${monitor_mode}
    patience: 10
    verbose: True

dataset:
  root: ${hydra:runtime.cwd}/mnt/dataset

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}/${model._target_.split(".")[-1]}
  sweep:
    dir: ${hydra.run.dir}
    subdir: job${hydra.job.num}_${hydra.job.override_dirname}
  output_subdir: hydra_configs
  job:
    name: emg2qwerty
    config:
      override_dirname:
        exclude_keys:
          - checkpoint
          - cluster
          - trainer.accelerator
